### ISSUE TITLE
failed to intall the x64 version 

### ISSUE THREAD

**Issue by souvis** [msys2/msys2#10]
I downloaded  msys2-x86_64-20161025.exe for my windows 10 x64 (10.0.14393), but there is no response when I execute the exe file either by directly double click or run as administrator,  I also try specify as win8 /win 7 compatibility in the property windows, redownload the exe , still cannot work.  As a result, I try the msys2-i686-20161025.exe it can be successfully installed.   How to resolve ?

**Comment by elieux** [comment]
The file works fine for me on multiple systems, but I cannot verify on the exact Windows 10 version you mentioned. Did you verify the SHA256 checksum as shown on http://msys2.org?

**Comment by mati865** [comment]
Cannot reproduce on 64-bit Win 10 Pro 1607.

**Comment by elieux** [comment]
Also works on 10.0.15058 (1703).

**Comment by souvis** [comment]
@elieux  It works now as a result of redownload one. Just as what you said, the SHA256 checksum is wrong, I found that the size of the former file is smaller than the correct one. Thank you elieux!
I has doubted that potential cause so I downloaded twice, bad lucky~ Thanks again!

**Comment by elieux** [comment]
Great. Thanks for reporting back.
