### ISSUE TITLE
Using msys2 bash in Visual Studio Code integrated terminal , many commands can not be used

### ISSUE THREAD

**Issue by CyangYu** [msys2/msys2#101]
I want to use msys2 bash in VS Code, it's prompt command not found, like ls, cp, gcc
But the bash of git bash work well in the terminal of VS Code

**Comment by Equim-chan** [comment]
Have you set $PATH properly?

**Comment by CyangYu** [comment]
I have resolved this problem, thank you

**Comment by martell** [comment]
closing :) Thanks for letting us know
