### ISSUE TITLE
Python 3.6.3 thinks it's running on Windows, not MSYS2

### ISSUE THREAD

**Issue by ctimmons** [msys2/msys2#105]
Python version 3.6.2 correctly sees that it's running on MSYS2, but 3.6.3 erroneously thinks it's running on Windows.

Is this a bug in the mingw64/mingw-w64-x86_64-python3 3.6.3-1 package?  Or is it a bug in Python itself?
    
Steps to reproduce:
    
Fresh install of msys2-x86_64-20161025.exe on Windows 8.1 (obtained from the msys2.org homepage).

1. Open a MSYS2 MinGW 64-bit bash prompt
1. Run `pacman -Syuu` twice, or until it says the system is up-to-date.
1. Run
```
pacman -S --needed git tar bsdtar binutils autoconf make xz \
curl libtool automake python python2 p7zip patch \
mingw-w64-$(uname -m)-gcc mingw-w64-$(uname -m)-python3-sphinx \
mingw-w64-$(uname -m)-tools-git
```
1. Running `pacman -Ss python` shows the following packages installed:
> mingw64/mingw-w64-x86_64-python3 3.6.3-1 [installed]
> msys/python 3.6.2-1 [installed]
1. Running `python` runs version 3.6.2.  It sees that it's running on MSYS2:
```
Python 3.6.2 (default, Sep  7 2017, 13:16:50)
[GCC 6.3.0] on msys
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'msys'
```
1. Running `python3` runs version 3.6.3.  It thinks it's running on Windows, not MSYS2:
```
Python 3.6.3 (default, Oct  5 2017, 07:28:46)  [GCC 7.2.0 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.platform
'win32'
```

**Comment by mati865** [comment]
This is expected behaviour, python{2,3} from `/usr` will identify as msys and native python{2,3} from `/mingw{32,64}` will identify as win32.
The same thing is for all other programs.

**Comment by ctimmons** [comment]
Thank you.
