### ISSUE TITLE
msys2 became unusably slow

### ISSUE THREAD

**Issue by szhorvat** [msys2/msys2#11]
I have been using msys2 occasionally to compile my package and its dependencies for Windows.  I do not use it for actual development, so I only start it every few months, to compile a release.

This time, after updating msys2, I noticed that it has become extremely slow.  A single `ls` took as long as 3.6 seconds to run.  This made running a `./configure` script plainly impossible.  Strangely, Task Manager does not show either high CPU or high disk usage.

How can I fix this to get a usable environment again?

What I tried so far:

 - Uninstalling msys2 (using the uninstaller) and making sure that `C:\msys64` is deleted, then reinstalling it.  It did not fix the problem, though now `ls` takes "only" 2 seconds.  **How can I fully reset the msys2 configuration and get a clean install?**

 - [Running as administrator ](http://stackoverflow.com/q/2835775/695132) doesn't help

 - The suggestions [here](http://bjg.io/guide/cygwin-ad/) only made things worse (create `/etc/passwd` and `/etc/groups` and remove `db` from `nsswitch.conf`).

I cannot recall doing anything on this machine in the past few months that could have affected msys2. It is still running under the same user. The OS is Windows 10. I also tried disabling real-time protection in Windows Defender, but it didn't help.  I am out of ideas at this point, and any suggestion (short of reinstalling Windows) will be most welcome.

**Comment by elieux** [comment]
> Uninstalling msys2 (using the uninstaller) and making sure that C:\msys64 is deleted, then reinstalling it. It did not fix the problem, though now ls takes "only" 2 seconds. How can I fully reset the msys2 configuration and get a clean install?

Did you update after re-installing? I'm curious to know if the slowdown was apparent even on a fresh (outdated) install. That would indicate that the cause of the slowdown isn't in our updates, but in your system.

> The suggestions here only made things worse (create `/etc/passwd` and `/etc/groups` and remove `db` from `nsswitch.conf`).

You're joined into a domain then? The various tips and tricks around the Internet sometimes even contradict each other, so it may be useful to try another trick (try replacing `MSYS2` with `Git for Windows` in the search term, it could produce more useful results).

Other than that, I can only recommend debugging with Strace, Procmon or Gdb.

**Comment by szhorvat** [comment]
> Did you update after re-installing? I'm curious to know if the slowdown was apparent even on a fresh (outdated) install. That would indicate that the cause of the slowdown isn't in our updates, but in your system.

I uninstall, then reinstalled.  The delay was still present.  Then I ran `pacman -Syuu` to update further.  That did not change anything.  The delay is still 2 seconds.

> You're joined into a domain then?

I am sorry, I am not sure what that means, therefore I assume that I am not.  I do not use Windows much. I did not knowingly change any network or user configuration.

Some more symptoms:

bash completion is very slow too.  [This article](https://gist.github.com/k-takata/9b8d143f0f3fef5abdab) talks about a situation where bash completion is slow, and one of the symptoms is that `echo ~*` takes very long.  This is *not* the case here.  `echo ~*` is instantaneous.  

This also shows that not every command is slow.  `echo` and `cd` are fast.  But `ls`, `which`, `date`, `clear` etc. are slow.  All these commands do their job instantaneously (e.g. `ls` displays the file list), but then have a 2 second delay before they exit.

I ran `strace date` (although I am not certain how to interpret the result), and again I see [all output](https://gist.github.com/szhorvat/ef0c06bdd40fbd46504e27df9ac847e3) appearing instantaneously, then there is a 2 second delay.

**Comment by szhorvat** [comment]
Just to rule out that it is bash that takes long to return, if I run `date && date && date`, then there is a 2 second pause after each of the three finishes (not only after all of them are done).

**Comment by mingwandroid** [comment]
You need to use procmon to see what happened just before the pauses.

**Comment by szhorvat** [comment]
@mingwandroid Thanks for the tip!  [Here's what Procmon shows me for `date.exe`](https://gist.github.com/szhorvat/461b8a3623cd85d92b77da21979551ea).  All entries are within 0.02 s of each other, then there is a 2 second delay, and finally there are two more entries.  I separated these with a newline for better visibility.

Is there anything that catches your eye here? I was not able to find a clue.

Or perhaps the events from `bash.exe` and `mintty.exe` are relevant too?  There are many more of those, so I didn't include them (I also did not notice anything suspicious there).

**Comment by szhorvat** [comment]
Another thing i noticed is that very occasionally running `date.exe` is not slow.  The few times I noticed this was always after leaving the mintty window alone for a while (in the background), and returning to it.  Then the first `date.exe` run was fast, and the subsequent ones were slow.  This does not happen consistently when I leave mintty in the background, though.

**Comment by szhorvat** [comment]
[This second file](https://gist.github.com/szhorvat/52dfb42be311b9d35a76e087d1890576) shows what happens when I try to use auto-complete in bash (which also involves a delay). The current directory was `/etc` and I was auto-completing `/etc/mtab`.

Note that there are three bash processes. I am not sure why.  One is started and then exists very quickl (PID 7544). Another one takes a 1 second pause (that's *precisely* 1 second) before it exits (PID 7544). I believe this is somehow related to the auto-completion delay.

**Comment by szhorvat** [comment]
This problem has nothing to do with msys2.  It happens in a standard `cmd.exe` window as well, with executables that are independent of msys (such as `where.exe`).

I will close the issue.

However, if you have any other suggestions about how to debug this, please do let me know!

**Comment by elieux** [comment]
> However, if you have any other suggestions about how to debug this, please do let me know!

It looks like some kind of timeout at the exit of a process. It doesn't seem to be related to registry nor file access, as shown by the procmon log. Ideas for further debugging:

- Although the procmon log doesn't show it, could you verify that there are no third-party DLLs loaded into processes?
- Check [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda).
- Would you be able to break the process execution during the delay and get a stacktrace? One way would be using Process Explorer (you can suspend a process and you can list all threads and get stacktraces for them), another way is with Gdb (you can attach to a running process if you know its PID, attaching automatically breaks the process execution). Maybe try both ways. Maybe you'll need to get debugging symbols.

> Note that there are three bash processes. I am not sure why.

Me neither, but I'm not surprised. Autocomplete doesn't have to be built in (not entirely), so it may need to spawn some processes. Also shells are generally fork-happy.

**Comment by mingwandroid** [comment]
VerySleepy is another tool that might help here.

**Comment by szhorvat** [comment]
I spent many fruitless hours on this.  But I finally found the cause.  It has to do with the display driver.  Rolling it back solved the problem.

This is a laptop with dual graphics (Intel + AMD) and the problem was the AMD software. Maybe it's because it is monitoring processes to see when to switch to AMD graphics.

**Comment by elieux** [comment]
Thanks for reporting back.
