### ISSUE TITLE
Autogen broken

### ISSUE THREAD

**Issue by aswin1980** [msys2/msys2#116]
Hi,
I'm trying to use media-autobuild_suite(https://github.com/jb-alvarado/media-autobuild_suite) to build ffmpeg for Windows. The suite creates msys2 system and builds the code.

However, the compilation fails due to a validation check on autogen.
When I run autogen inside msys2, this is the error i'm getting.
C:/media-autobuild_suite/msys64/usr/bin/autogen.exe: error while loading
> shared libraries: msys-guile-2.0-22.dll: cannot open shared object file: No
> such file or directory
 
The guile file inside the msys64 folder is msys-guile-2.2-1.dll.

When I install the msys2(64 bit) manually, dowloaded from the site, the guile version is msys-guile-2.0-22.dll 

According to the group (https://github.com/jb-alvarado/media-autobuild_suite/issues/639) msys2 is broken.

Any idea how to solve it?

Thanks

**Comment by LigH-de** [comment]
According to the pacman package cache, autogen-5.18.12-1 was the last installed autogen version on my installation, not 5.18.4 as in the reported manual installation.

In my var/log/pacman.log I find the first installation of autogen and an update, as well as for libguile:

`[2017-05-24 14:44] [ALPM] installed libguile (2.0.11-3)`
`[2017-05-24 14:44] [ALPM] installed autogen (5.18.4-2)`

`[2017-06-06 16:33] [ALPM] upgraded libguile (2.0.11-3 -> 2.0.14-1)`
`[2017-06-06 16:33] [ALPM] upgraded autogen (5.18.4-2 -> 5.18.12-1)`

`[2017-11-22 11:58] [ALPM] upgraded libguile (2.0.14-1 -> 2.2.2-1)`
But no equally recent update of autogen.

So I wonder if any other application of MABS required a newer libguile, and autogen fell behind.

**Comment by mati865** [comment]
Rebuilding `autogen` should fix it.

**Comment by LigH-de** [comment]
MABS will build autogen now on its own. So you can probably close this.
