### ISSUE TITLE
Can't install on Windows 10 x64 - MSYS2 64bit 20161025

### ISSUE THREAD

**Issue by d3im** [msys2/msys2#12]
Installation progress is at 66 % - several bash jobs are running - CPU utilization 100%. After a while there is popup error:

> Error during installation process (com.msys2.root.base):
> Execution failed (Unexpected exit code: 254): "C:\msys64\usr\bin\bash.exe --login -c exit"

I click ignore then some script starts, then I click run msys2, but nothing shows only window that immediately disappears.

bash jobs still running so I try to kill them. No progress.
Same for 20160921 :-(

Windows 10 Home 1607 x64

SHA256 of installation file is correct.

**Comment by elieux** [comment]
Can you try installing manually from the [archive](http://repo.msys2.org/distrib/x86_64/msys2-base-x86_64-20161025.tar.xz)? Extracting with 7-Zip should be enough. Then run `msys2_shell.cmd`. You should be able to what's the issue there.

**Comment by genusistimelord** [comment]
I to am getting this error on a new windows 10  professional 1607  Build 14393.1066
I tried doing what you said with the archive and all it does is crash the command prompt. Even if i run as administrator. My installer however would not tell me the error it was having. it just hanged at the login script part which is around 66% complete on the installer.

**Comment by elieux** [comment]
I now realize this could have a connection to a problem I had on my Windows 10 (1703) few days ago -- I ran a big `pacman -Syu` and it slowed down to a crawl despite CPU running at 100 %. The problem seemed to be tens of runaway `bash` processes (lowering their priority allowed the upgrade to finish).

**Comment by genusistimelord** [comment]
OK, I shall give that a try and see what happens with the installer itself. Hopefully, it works XD.

**Comment by elieux** [comment]
I think the crash would be more interesting to investigate, but any data is useful at this point.

**Comment by elieux** [comment]
I just tried installing and upgrading on another Windows 10 (1607) and no problems there. I also tried running `while true; do bash -c exit; echo -n .; done` for some time and all of those exited correctly.

**Comment by genusistimelord** [comment]
Yeah my other Windows 10 (1607) worked just fine and is running msys2, however this one wont make it past the installation process and still is hanging on 66%. It started up 2 bash files and one is using 100% of a single core in my processor. This is a fresh installation of Windows 10 that has the latest updates.

**Comment by genusistimelord** [comment]
'while' is not recognized as an internal or external command,
operable program or batch file.

is what i get in my CMD Bash on windows. I will go look up the solution.

**Comment by elieux** [comment]
That command is supposed to be run inside Bash, not in Cmd.

Have you tried looking into the manual installation (extract the `.tar.xz` and run `msys2_shell.cmd`)?

**Comment by genusistimelord** [comment]
yes i have tried that before. All it does is open up then close very quickly.

Microsoft Windows [Version 10.0.14393]
(c) 2016 Microsoft Corporation. All rights reserved.

C:\WINDOWS\system32>cd C:\msys64

C:\msys64>msys2_shell.cmd

C:\msys64>

It shows nothing here as well.

**Comment by elieux** [comment]
Can you try this?
```
C:\msys64> usr\bin\mintty -h always -
```

**Comment by genusistimelord** [comment]
sorry for the late reply. I will try this today as I did not have access to the PC in question until today.

**Comment by outwitevil** [comment]
Hello,
I'm having the same error on a win7pro laptop.
I downloaded the installer today after completely removing my old version via the control panel.
![msys2_installer_error](https://cloud.githubusercontent.com/assets/294029/25344146/35cb20de-28df-11e7-93a5-cf05be460993.png)
I will attempt to do the manual install as well next but I wanted you to be aware of this.

**Comment by outwitevil** [comment]
Here's what I get. 
![msys2_shell_error](https://cloud.githubusercontent.com/assets/294029/25344440/22a7786c-28e0-11e7-8759-6c64742e5b87.png)

**Comment by outwitevil** [comment]
Just reran the process (wiping the c:\msys dir each time) for each older release in the archive from the link you provided.  The only one that worked was the first one.
msys2-base-x86_64-20150916.tar.xz
This is the same version I was previously running.

**Comment by elieux** [comment]
Okay, that looks a bit familiar. Let's try the [fork() failure debugging steps](https://cygwin.com/faq.html#faq.using.fixing-fork-failures) from the Cygwin user guide, especially:
- check if you're running anything from [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda)
- check for suspicious (third-party) DLLs loaded into MSYS2 processes (using [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer), [ListDLLs](https://technet.microsoft.com/en-us/sysinternals/bb896656.aspx), [LoadedDllsView](http://www.nirsoft.net/utils/loaded_dll_view.html)...)
- run `set MSYS=detect_bloda` before running `usr\bin\bash -li` to see if it reports anything
- finally, try running `autorebase.bat`

**Comment by genusistimelord** [comment]
the command you gave worked however i am also getting the GPME errors but i think thats caused by my works Sonicwall. I can bypass those checks by changing a setting but i forgot where it was lol.

**Comment by AsukaLangleyfag** [comment]
I've got the same case, thou on pre-creators win10.
It was: non of installers worked.
Only chocolatey one worked. I suspect AV because i've removed it too (was CIS).

**Comment by elieux** [comment]
@AsukaLangleyfag, you mean that after you removed CIS, you tried all the installers and only the Chocolatey one worked?

**Comment by AsukaLangleyfag** [comment]
@elieux no, exactly the opposite. Only Chocolatey worked. Now every installer works, even one made myself with https://github.com/msys2/msys2-installer

**Comment by elieux** [comment]
Closing as *some* issue got resolved. In case someone is still experiencing difficulties with the installer, please open a new issue.
