### ISSUE TITLE
Improvements from WSL

### ISSUE THREAD

**Issue by firelizzard18** [msys2/msys2#13]
Could MSYS2 benefit from new windows features that were introduced for WSL? I'm thinking something like using [pico processes](https://blogs.msdn.microsoft.com/wsl/2016/05/23/pico-process-overview/) instead of Cygwin's brilliant-but-god-awful-hack implementation of `fork()`. If so, do the MSYS2 developers have any intention of doing this?

**Comment by Alexpux** [comment]
MSYS2 use Cygwin runtime as base

**Comment by elieux** [comment]
As @Alexpux implied, any efforts to adapt MSYS2 to take advantage of kernel improvements in Win10 would need to be coordinated with Cygwin developers. I suggest you try [their mailing list](https://www.cygwin.com/ml/cygwin/) and we can chime in if needed.

If you're interested in a POSIX layer that tries to do this, look into [Midipix](http://midipix.org) (work in progress).
