### ISSUE TITLE
libcurl support

### ISSUE THREAD

**Issue by fejoa** [msys2/msys2#15]
Hi there, just tried building a little test application following this recipe: https://fatchoco.wordpress.com/2009/03/01/using-curl-in-mingw/

Running the resulting `simple.exe` gives me:
`The procedure entry point SSL_COMP_free_compression_methods could not be located in the dynamic link library C:\msys64\mingw32\bin\libcurl-4.dll.`

Running windows 8.1 64-bit with 64-bit MSYS2 build system but with `i686` toolchain. Can you give it a try? I'd love to know whether I'm missing any packages? It might be an upcoming [issue](https://github.com/Attnam/ivan/issues/257) with our open source game, going forward.

**Comment by elieux** [comment]
I think that comes from mixing the curl you just build and the curl that comes with MSYS2. If I just download the (latest) curl archive, go into `docs/examples` and run `gcc simple.c -Wall -lcurl -o simple.exe`, then running `./simple` works. I assume you have `mingw-w64-i686-toolchain` and `mingw-w64-i686-curl` installed.

Is your MSYS2 fully updated (see [installation guide](https://github.com/msys2/msys2/wiki/MSYS2-installation#iii-updating-packages))?

**Comment by fejoa** [comment]
Thanks! It works as you say when running `./simple` from the `MINGW32` shell. But not when clicking on the `simple.exe`. 
And what do you know? if I type `./ivan` to play my compiled game, it runs! But how do I compile using msys2 to produce a standalone executable for distribution zip file to other windows users?

**Comment by elieux** [comment]
Okay, closing issue.

The build products depend on some libraries, you can see which using [Dependency Walker](http://www.dependencywalker.com/), ldd, ntldd or other tools. You can set your `PATH` so it points to `C:\msys64\mingw32\bin` for development and testing. For distribution, you can copy those libraries to the same directory as your executable and pack everything into your distribution ZIP (subject to respective licenses). There are methods to automate the process, see our [Distributing wikipage](https://github.com/msys2/msys2/wiki/Distributing).

You can also try to build statically to bake in the libraries directly into your executable.
