### ISSUE TITLE
mingw32, mingw64, gcc which should I use??

### ISSUE THREAD

**Issue by 424778940z** [msys2/msys2#16]
what's the difference between mingw and gcc in msys2?

I'm trying to work with qt under msys2, but I can't find any qt package for the standard gcc, all of them are for mingw.
And mingw64 don't share headers (I mean those -devel package) with mingw32, that's means If I want install libraries, I have to do them for both, it's really painful to change ever single i686 to x86_64 when dealing with pacman. is there a easier way?

If we have gcc why there is also mingw here? Yes, mingw is useful in many ways, but manage their package is really painful.

**Comment by tresf** [comment]
@424778940z Pardon my lack of knowledge with the project, I'm just passing by this bug tracker... 

I've had several problems getting mingw compiling a qt project.  From my memory, the version of qt available from pacman did not ship with pthreads support, which is a main reason to use mingw-w64 and msys2 to begin with.

Our current solution is not very elegant, but we [use the pacman version of qt](https://github.com/LMMS/lmms/wiki/dependencies-windows#setup-basic-build-environment) and then [clobber it with an Ubuntu PPA version](https://github.com/LMMS/lmms/blob/stable-1.2/cmake/msys/msys_helper.sh#L35-L52), giving us the DLLs needed for pthreads to work.

Next, we [use cmake to setup the environment properly](https://github.com/lmms/lmms/blob/stable-1.2/cmake/modules/MinGWCrossCompile.cmake#L10).

But then we hit some [POSIX vs Win32 path problems](https://github.com/LMMS/lmms/wiki/dependencies-windows#setup-additional-workarounds) and have to hack some symlinks to fix them.

>  mingw64 do't share headers

This is a good point however generally the headers are only installed when the library is available for linking, so this is probably a good thing, no?

**Comment by 424778940z** [comment]
@tresf I saw these packages come with mingw-w64 and qt-static.
mingw64/mingw-w64-x86_64-libwinpthread-git
mingw64/mingw-w64-x86_64-winpthreads-git 

seems compiler have pth support, if the qt bins available on pacman don't have pth support, maybe you can download qt source and compile pth then put them into qt's folder. or just compile the whole qt source with mingw, don't use the pacman one.

I'm not use pth on my qt project, i'm not sure about this, but at least full compile should work.

**Comment by tresf** [comment]
@424778940z Regardless of the specific qt issues we encountered, I still think you'll find the cmake setup linked above helpful.  What build system are you using?

**Comment by mati865** [comment]
> what's the difference between mingw and gcc in msys2?

There are three subsystems:
1. msys2 - emulated POSIX, using libs and headers from `/usr`
2. mingw32 - native 32-bit MinGW-w64, using libs and headers from `/mingw32`
3. mingw64 - native 64-bit MinGW-w64, using libs and headers from `/mingw64`

They have different ABI's so you cannot mix them.

> I'm trying to work with qt under msys2, but I can't find any qt package for the standard gcc, all of them are for mingw.

MSYS2 project focuses on native software, to use it open MINGW32 or MINGW64 shell and if you have `mingw-w64-${CARCH}-toolchain` installed `gcc` will use mingw-w64 libs and headers.

>  it's really painful to change ever single i686 to x86_64 when dealing with pacman. is there a easier way?

There is unofficial [wrapper for pacman](https://github.com/renatosilva/pactoys/tree/master/source/pacboy)

> If we have gcc why there is also mingw here? Yes, mingw is useful in many ways, but manage their package is really painful.

GCC is the compiler, `msys2-runtime*` and MinGW-w64 are __different__ and __incompatible__ environments for GCC.
While MSYS2 strongly prefers native software not everything can be build with MinGW-w64 so it's build with emulated POSIX layer.

**Comment by elieux** [comment]
I'm closing this ticket because it doesn't describe an outstanding issue, but please feel free to ask further questions here or through [our other communication channels](http://www.msys2.org/#support-or-contact).

**Comment by tresf** [comment]
> this ticket because it doesn't describe an outstanding issue

Although this is true, the task of building a small Qt project from scratch using msys2 is a clear task that the OP does not yet seem to have resolved.

This project (or perhaps a community support channel) seems the best place for discussion.

Do you mind if @424778940z continues to use this thread to discuss his struggles?  I haven't seen a response stating his build environment or what difficulties he's experiencing.  Due to the popularity of msys2 as well as Qt, his question seems quite relevant to the success of the project as a whole, no?

**Comment by 424778940z** [comment]
Sorry for late reply.
I setup environment with mingw-64-x86_64 and qt-static, it works.
Thanks for both of you guys.

**Comment by elieux** [comment]
> Do you mind if @424778940z continues to use this thread to discuss his struggles?

Go on, I don't mind. I unfortunately can't help with Qt at all, so I'll leave it to others. If a bug in our Qt build is identified, just file an issue for that bug (and link back here for reference).

> There is unofficial wrapper for pacman

I added a mention of `pacboy` to our wiki: https://github.com/msys2/msys2/wiki/Using-packages
