### ISSUE TITLE
Unable to configure proxy on Windows 7

### ISSUE THREAD

**Issue by lcota** [msys2/msys2#20]
I'm unable to run pacman update or use the maintenance tool.   
From browsing google results, I've tried:
- setting proxy variables in the network.xml file in c:/msys64/
- modifying environment variables to include proxy information (with and without password)

What else can I do to get pacman/msys2 to work with my proxy?

**Comment by elieux** [comment]
> maintenance tool

Let's try pacman first. Setting HTTP_PROXY and http_proxy doesn't work? Can you also try a different mirror (`/etc/pacman.d/mirrorlist.*`)?

<https://stackoverflow.com/questions/197904/how-do-i-use-cygwin-behind-the-corporate-firewall>

**Comment by lcota** [comment]
@elieux I had tried setting the proxy variables before, though I never used the http:// prefix, as few other tools have required it. Adding the http:// to the proxy environment variables fixed the issue.
