### ISSUE TITLE
libzip missing zipconf.h

### ISSUE THREAD

**Issue by tenspd137** [msys2/msys2#21]
Hello -

I was trying to compile something using libzip.  It appears that the zip.h header needs zipconf.h, which is nowhere in the include directories.  I looked around and I saw various things about changing lines in the CMake files, etc.

Any help would be appreciated!

**Comment by elieux** [comment]
Sorry for the late response.

You need to use pkg-config to get the right flags for building with libzip:

```
$ pkg-config libzip --cflags # compile flags
-ID:/msys64/mingw64/include -ID:/msys64/mingw64/lib/libzip/include
$ pkg-config libzip --libs # link flags
-LD:/msys64/mingw64/lib -lzip -lz
```

I don't know how CMake interfaces with pkg-config, so I'll have to let you figure that out yourself.

**Comment by elieux** [comment]
Closing this issue, but we can continue to discuss if you need anything.

**Comment by tenspd137** [comment]
Thanks!  I was unaware of how to do that.  Much appreciated!
