### ISSUE TITLE
using msys2 shell tools inside msys2 mingw emacs

### ISSUE THREAD

**Issue by nicferrier** [msys2/msys2#22]
I'm playing with Windows 10 (hey, it's a dev OS now, did you hear?).

I installed mingw emacs from msys2 (mainly because I like msys2) but I'm struggling to make emacs work sensibly with it.

Emacs on Windows needs a lot of shell helper stuff, things like grep and find. With msys2 these seem most sensible to run from msys2? (rather than mingw? don't seem to have a mingw bash anyway)

There's a lot of tricky things. The HOME's are different - does it make sense to try to make them the same? Could I ln the .emacs.d and the .ssh and stuff like that even?

I'm not even sure how to start a shell safely. Setting emacs' shell-file-name to msys2's bash doesn't result in an msys2 environment, the shell startup files coming from somewhere else.

Also I get ugly startup with such a mechanism:

```
bash: cannot set terminal process group (-1): Inappropriate ioctl for device
bash: no job control in this shell
/usr/bin/cut: you must specify a list of bytes, characters, or fields
Try '/usr/bin/cut --help' for more information.
]0;/c/sandbox
nicferrier@DESKTOP-89L3QJF MSYS /c/sandbox
$ ]0;/c/sandbox
```
the /sandbox stuff is me of course... I can't see where the cut is coming from.

I can use the ~/.emacs_BASH file to normalize the shell environment but only after it's started.

Help! Anyone done this offer some tips?

**Comment by elieux** [comment]
> Emacs on Windows needs a lot of shell helper stuff, things like grep and find. With msys2 these seem most sensible to run from msys2? (rather than mingw? don't seem to have a mingw bash anyway)

Well, there's no mingw-w64-bash, but you can start a "MINGW64 shell", maybe like this: `/usr/bin/env MSYSTEM=MINGW64 /usr/bin/bash -li`. I don't know if emacs supports a command like this, but essentially you need to put `MSYSTEM=MINGW64` into the environment before starting bash.

> There's a lot of tricky things. The HOME's are different - does it make sense to try to make them the same? Could I ln the .emacs.d and the .ssh and stuff like that even?

Yeah, you can share bits of your Windows HOME with MSYS2, or even the whole HOME. If it makes sense has to be judged for each application (and I'm no emacs expert). `/etc/nsswitch.conf`<https://cygwin.com/cygwin-ug-net/ntsec.html> may come in handy (look for `db_home: windows`).

> I'm not even sure how to start a shell safely. Setting emacs' shell-file-name to msys2's bash doesn't result in an msys2 environment, the shell startup files coming from somewhere else.

What do you mean? It looks like an MSYS prompt in your quote.

> bash: cannot set terminal process group (-1): Inappropriate ioctl for device> bash: no job control in this shell

Seems like emacs doesn't provide a tty. No idea what to do.

> /usr/bin/cut: you must specify a list of bytes, characters, or fields

Probably from `/etc/bash.bashrc`. But I don't see why. If you could start bash with an `-x` argument, that could show what's happening.

**Comment by nicferrier** [comment]
Thanks! All good. I think basically setting MSYSTEM seems to make a massive difference to internal tools using things like grep and find.

The trouble is I'm still having to start it with a bat file, pinning removes it's understanding of where it's at. There doesn't seem to be a way to get Windows 10 to have a pointer to an app that is going:

mingw64 emacs-binary

but hey ho. Guess I can use the bat file for a while until I work it out.

Thanks again.
