### ISSUE TITLE
mingw-w64-x86_64-nodejs doesn't come with npm and I can't understand why

### ISSUE THREAD

**Issue by nicferrier** [msys2/msys2#24]
I used to use Arch back in the day so hoped I'd be able to work out how some of this works.

But I can't seem to work out where the repos of the package definitions are. 

There's nothing in PKGINFO or BUILDINFO and I'd like to know how the node package was built so that I can understand why it doesn't have npm included and maybe contribute.

I thought I remembered that the upstream package repository was referenced in the PKGBUILD but perhaps that's only convention on Arch and it might have changed.

Is there a way to trace a package back to it's build repository?

**Comment by mati865** [comment]
Npm build hangs: https://github.com/Alexpux/MINGW-packages/issues/2249

Maybe updating Node.js and Npm could help but case is still open.

**Comment by elieux** [comment]
> Is there a way to trace a package back to it's build repository?

There's no actual link anywhere in the package (as IIRC is the case with many package managers), but the [wikipage about creating packages](https://github.com/msys2/msys2/wiki/Creating-Packages) notes that our packages come from two repositories (msys2-packages, mingw-packages) and where to find them ([alexpux/msys2-packages](https://github.com/alexpux/msys2-packages), [alexpux/mingw-packages](https://github.com/alexpux/mingw-packages)). If you think there's a more obvious place to note this information, please tell, improving docs is always good.

**Comment by elieux** [comment]
Seems like we got NPM now. We're still missing `npm.cmd` though. :)
