### ISSUE TITLE
Installing from command line

### ISSUE THREAD

**Issue by atmosx** [msys2/msys2#29]
Hello,

I'm trying to install `msys2` on a *MS Win 2016 Nano Server* without success. Is there any way to install `msys2` from msdos or powershell? I managed to do so using Chocolatey and I can think of a few uncoventional methods (install on Windows Server 2016, create a zip and just unzip the dir on Nano), I'm not sure if this is going to work.

The problem with the Chocolatey installation is that messes up the paths, changing the order, results to breaking quite a few things so... I'm trying to figure out a way to go around chocolatey.

Thanks

**Comment by elieux** [comment]
Sure, you can just extract the `.tar.xz` that's available from http://repo.msys2.org/distrib/.
