### ISSUE TITLE
the usage of  sys/ioctl.h under  /usr/include 

### ISSUE THREAD

**Issue by redliu312** [msys2/msys2#34]
I tried to build a open source project named "ipmitool".
**This tool can be build under cygwin.**  So I used the same steps to build it under mingw64 of msys2.
But I encountered an problem as follow:
```c
helper.c:41:44: fatal error: sys/ioctl.h: No such file or directory
 #include <sys/ioctl.h>  /* For TIOCNOTTY */
```
Then I thought maybe I should add the /usr/include to the PATH variable because the /sys folder is under /usr/include in msys2.

But the error is still the same, is this  a issue or I misunderstand something?

**Comment by mati865** [comment]
`/usr` and `/mingw64` are totally different subsystems and cannot be mixed.
MINGW64 shell will use only native Windows libs and headers.

**Comment by redliu312** [comment]
@mati865 
Thanks a lot.
Now I understand that:

- mingw32 - to build 32-bit native windows executables.
- mingw64 - to build 64-bit native windows executables.
- msys2 - to build  msys2 executables,  need the **msys-2.0.dll** when distributing

This is why I can build the project(originally on linux) under msys2, but can't do the same thing on mingw64 and that's why "/usr and /mingw64 are totally different subsystems and cannot be mixed". Am I right?

**Comment by elieux** [comment]
That's correct. When something builds successfully for Cygwin, it should build for msys2 as well, but no guarantees for mingw.
