### ISSUE TITLE
Bad address when using ruby.exe in Msys2

### ISSUE THREAD

**Issue by yoshiwaan** [msys2/msys2#36]
Hi,

I've been a long time user of Msys2 and am very happy with it. Generally speaking there are some things I install with Chocolatey, namely programming languages, so I can use them easily outside of Msys2.

I've been having an issue with ruby (2.2.4 and 2.3.3) installed via chocolatey in Msys2. Namely, the following always happens:
```
$ ruby
bash: /c/tools/ruby22/bin/ruby: Bad address
```
In a cmd prompt it works as expected.
Ruby was installed by running `choco install ruby --version 2.3.3` in an admin cmd prompt, which adds it to PATH. There's nothing special about that installation

I have a normal Msys2 installation (just updated a few minutes ago).  Not sure that it makes much of a different but I set the following environment variables when starting Msys2:
```
MSYSTEM=MSYS
TERM=cygwin
PATH=/usr/local/bin:/usr/bin:/bin:%PATH%
HOME=%USERPROFILE%
MSYS2_PATH_TYPE=inherit
```
I use ConsoleZ as an emulator.

How would I go about debugging this? Is there any more useful information I can provide.

**Comment by elieux** [comment]
My first guess would be a DLL conflict. Run [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx), filter by *Process Name = ruby.exe*. Look for records indicating DLL loads (you can use custom filters or the predefined filters in the toolbar to help you with that). Does your Ruby load any non-Microsoft DLL from outside `C:\tools\ruby22`?

**Comment by yoshiwaan** [comment]
![image](https://user-images.githubusercontent.com/9516822/27196545-b478009c-51bf-11e7-84cc-e441a8d0acbf.png)
 
Is this what you're after?

I have another machine with the same setup (same chocolately ruby version, msys2 64 bit (maybe a different version), windows 10 64 bit) and it works, so I'm not sure what the deal is here.

Is there some way to enable further debugging from within the msys2 bash shell?

**Comment by elieux** [comment]
> Is this what you're after?

Yeah. Looks fine.

> Is there some way to enable further debugging from within the msys2 bash shell?

You can try setting `MSYS=error_start:...` as described in `msys2_shell.cmd`, but I'm not sure if that will catch the error. You can try Strace.

Also try outside of of ConsoleZ (`msys2_shell -defterm`).

**Comment by yoshiwaan** [comment]
Thanks @elieux. That helped me find the issue.

The combination of these environment variables I was setting when running the Msys2 shell in ConsoleZ caused the issue:
```
PATH=/usr/local/bin:/usr/bin:/bin:%PATH%
MSYS2_PATH_TYPE=inherit
```
For some reason something in the path wasn't being converted to unix paths properly when using that combination. In any case by taking out the PATH variable everything works now, as Msys2 prepends the relevant unix paths to PATH inside the shell (I'm guessing it didn't at one point, which is why it was there in the first place)

Out of interest can you explain how the `MSYS=error_start` variable works? In msys2_shell.cmd it seems to point to qtcreator.exe, which doesn't exist in my msys2 installation
