### ISSUE TITLE
error: GPGME error: Invalid crypto engine

### ISSUE THREAD

**Issue by Ambush80** [msys2/msys2#38]
Hi all, i have reinstalled following the official reccomendations, and tried numerous other fixes as well, absolutly nothing works, i cannot get msys2 to update or download any packages, i have even removed things like git and checked for any other other software that could interfere with msys2 as far as i can tell all is good, does anyone have any idea how to fix this ?

I checked the installer log and this was shown
gpgkeys: key EDB309EEAA624B9D15A241F58A72C84FA324E404 not found on keyserver

I am using the latest installer 
My OS is Server 2012 R2 Workstation : Xeon X5687 if that helps

**Comment by elieux** [comment]
Please paste a log that shows the command you tried and all the output including the error.

Anyway, it still seems like interfering software. First check [BLODA](https://cygwin.com/faq/faq.html#faq.using.bloda), then list loaded DLLs using [Process Monitor](https://technet.microsoft.com/en-us/sysinternals/processmonitor.aspx) (filter by *Process Name = pacman.exe* and look for records indicating DLL loads (you can use custom filters or the predefined filters in the toolbar to help you with that).

**Comment by Ambush80** [comment]
hi, thanks for the response, i just gave a go at the unsigned method and that appears to have worked, so i am thinking you are right on that being a software problem. 
Its kinda strange as i did have it working previously without issue, that being said i do have a load of other build tools installed as well since then.
prob a stupid question but is it ok to use the unsigned method ?

**Comment by Ambush80** [comment]
here is one log as well
[pacman debug.txt](https://github.com/msys2/msys2/files/1060857/pacman.debug.txt)

**Comment by elieux** [comment]
> prob a stupid question but is it ok to use the unsigned method ?

You're exposing yourself to the (so far unlikely) possibility of downloading and installing malicious packages (either from a hacked mirror or through MitM).

Can you list the DLLs as I described previously?

**Comment by Ambush80** [comment]
yep i have them here,

C:\msys64\usr\bin\msys-2.0.dll
C:\Windows\System32\guard64.dll
C:\Windows\System32\imm32.dll
C:\Windows\System32\version.dll
C:\Windows\System32\ole32.dll
C:\Windows\System32\combase.dll
C:\Windows\System32\oleaut32.dll
C:\Windows\System32\shlwapi.dll
C:\Windows\System32\fltLib.dll
C:\Windows\System32\KernelBase.dll
C:\Windows\System32\ntmarta.dll
C:\Windows\System32\ntdll.dll
C:\Windows\System32\ws2_32.dll
C:\Windows\System32\NapiNSP.dll
C:\Windows\System32\nlaapi.dll
C:\Windows\System32\mswsock.dll
C:\Windows\System32\dnsapi.dll
C:\Windows\System32\winrnr.dll
C:\Windows\System32\sechost.dll

hope it helps

**Comment by elieux** [comment]
I don't recognize some of these. Can you check if they're all from MS? Maybe an easier way is to run `pacman -S bash`, let it wait on the prompt, and look at DLLs using [Process Explorer](https://technet.microsoft.com/en-us/sysinternals/processexplorer.aspx).

**Comment by Ambush80** [comment]
guard64.dll is part of comodo internet security as far as i can tell that is the only one that is not microsoft

**Comment by Ambush80** [comment]
its possible that this could be causing the problem, it can be a very aggressive security suite, sometimes a real PITA, i am not sure how or why it would be causing a problem though

**Comment by elieux** [comment]
Well, you could've noticed the one Comodo product on BLODA and said something about another one being installed on your machine. :D

**Comment by elieux** [comment]
Anyway, the problem is when the injected DLL messes up the memory space of the process. GPG is particularly sensitive to this due to its anti-tampering features.

**Comment by elieux** [comment]
I suggest adding GPG executables (or even the whole MSYS2 installation) to the exception list in your CIS configuration.

**Comment by Ambush80** [comment]
lol my bad, i didn't see that sorry for wasting you time
