### ISSUE TITLE
[Package build]

### ISSUE THREAD

**Issue by Salamandar** [msys2/msys2#4]
Hi there !
I'm trying to build gnome-calculator (mingw64-x86_64, as only the mingw64-i686 is in the repos).
I have some trouble with the `data/gnome-calculator.desktop` and `data/gnome-calculator.appdata.xml` files (generated from the *.in files) : 

    make[1]: *** No rule to make target `gnome-calculator.desktop', needed by `all-am'.  Stop.

I "fixed" this by copying the files from the already existing mingw-i686 install, but that doesn't really solve the problem.
Is it a known issue/bug with msys/other ?
Other than that, the pkg builds and runs fine on mingw64.

**Comment by elieux** [comment]
Hi, I see no such error using our [mingw-w64-gnome-calculator `PKGBUILD`](https://github.com/Alexpux/MINGW-packages/blob/master/mingw-w64-gnome-calculator/PKGBUILD). What method of building did you use?

**Comment by Salamandar** [comment]
Yeah that's the problem : I can't see any errors here.
Well i followed your wiki :
```
export MINGW_INSTALLS=mingw64
makepkg-mingw -sLfe
```

**Comment by elieux** [comment]
How is "no errors" a problem? :D I just tried the exact same commands as you and I see this in the logs:
```
make[1]: Entering directory '/w/dev/mingw-packages/mingw-w64-gnome-calculator/src/build-x86_64-w64-mingw32/data'
  ITMRG  gnome-calculator.appdata.xml
  ITMRG  gnome-calculator.desktop
  GEN      org.gnome.calculator.gschema.valid
make[1]: Leaving directory '/w/dev/mingw-packages/mingw-w64-gnome-calculator/src/build-x86_64-w64-mingw32/data'
```

**Comment by elieux** [comment]
Maybe you're missing `intltool`? What does `pacman -Ss intltool` say?

**Comment by Salamandar** [comment]
I got intltool : 

```
 ❯ pacman -Ss intltool                                               [15:28:14]
msys/intltool 0.51.0-2 (base-devel) [installé]
    The internationalization tool collection
```

**Comment by elieux** [comment]
Can you put your build logs on pastebin/gist/... and link to them here?

**Comment by Salamandar** [comment]
Sure ! 
https://geekolloc.fr/zerobin/?bca4f319a605f5e5#mh7CBYkEOOX5sMnx679Ga/iN2pHPGQfgIVXlBAv2zNo=

**Comment by elieux** [comment]
This looks suspicious:
```
process_begin: CreateProcess(NULL, /mingw64/bin/glib-compile-resources --generate-dependencies --sourcedir=../../gnome-calculator-3.16.2/data/ ../../gnome-calculator-3.16.2/data/gnome-calculator.gresource.xml, ...) failed.
```

Otherwise, your log is differing in other things, like missing `VALAC` invocations. Is your system up-to-date?

See my log here: http://pastebin.com/gCcVaZav

**Comment by elieux** [comment]
Ha! It says `C:/bin/make`. Do you have this in your `PATH`?

**Comment by Salamandar** [comment]
Ho shit. Yes, that's my working computer so I don't know all the the env customizations.
Thanks for the good eye you got ;) I'll fix my PATH

    /c/bin:/c/bin/TypeScript/1.4:/home/FelixP/bin:/c/bin:/mingw64/bin:/mingw32/bin:/usr/local/bin:/usr/local/sbin:/mingw64/bin:/usr/bin:/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/

then retry the build.
BTW, I got 3 (more or less related questions).
* What's the difference between mingw64 and MSys ? Some packages are provided by both here, that's a bit disorienting.
* Should I favor mingw64 packages or msys2 ?
* How can I suggest package builds ? (like this one, in x86_64 and not i686)

**Comment by Salamandar** [comment]
Not so surprisingly… That works perfectly fine now !

**Comment by elieux** [comment]
> Not so surprisingly… That works perfectly fine now !

Cheers.

> What's the difference between mingw64 and MSys ? Some packages are provided by both here, that's a bit disorienting.
> Should I favor mingw64 packages or msys2 ?

Answers to both should be clear from this wikipage: https://github.com/msys2/msys2/wiki/MSYS2-introduction
If not, post further questions (available communication channels are described at the bottom of http://www.msys2.org).

> How can I suggest package builds ? (like this one, in x86_64 and not i686)

There's no pre-made process for this. I will relay this information to @Alexpux, who does our package builds.

**Comment by Salamandar** [comment]
Thanks for all the answers ;)
