### ISSUE TITLE
cmake package not working properly

### ISSUE THREAD

**Issue by fuzzyTew** [msys2/msys2#41]
Hi,

If I do `pacman -S cmake`, I get this error:
```
$ cmake ..
CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
CMake Error: CMAKE_C_COMPILER not set, after EnableLanguage
CMake Error: CMAKE_CXX_COMPILER not set, after EnableLanguage
-- Configuring incomplete, errors occurred!
```

I then try `pacman -S mingw-w64-x86_64-cmake`, and get this error:
```
$ cmake ..
CMake Error: Could not find CMAKE_ROOT !!!
CMake has most likely not been installed correctly.
Modules directory not found in
/mingw64/share/cmake-3.6.2
CMake Error: Error executing cmake::LoadCache(). Aborting.
```

Googling around, it seems that what people are doing is removing the cmake package and installing cmake using the official windows installer from cmake's website ( https://stackoverflow.com/questions/37365355/cmake-msys-makefiles-generator-missing ).

**Comment by elieux** [comment]
> CMake Error: CMake was unable to find a build program corresponding to "Unix Makefiles".

I think you're missing `make` in this case.

The second error looks weird. Is your installation up to date? My output:

```
$ pacman -Q mingw-w64-x86_64-cmake
mingw-w64-x86_64-cmake 3.8.1-3
$ which cmake
/mingw64/bin/cmake
$ cmake ..
-- Building for: Visual Studio 14 2015
[...]
```

**Comment by elieux** [comment]
Closing for lack of response.
