### ISSUE TITLE
change C drive mount point

### ISSUE THREAD

**Issue by sohnryang** [msys2/msys2#42]
Hello, I use Windows tools in msys2.

Since msys2 mount windows drive like `/c`, `/d`, etc...

Windows tool which receives arguments like `/c`, `/d`, msys2 interferes proper execution of tools.

How can I change mount point from `/c` to something like `msys2drive/c`?

**Comment by elieux** [comment]
All absolute paths start with a slash. Changing the mount point wouldn't help you much with that, although it [can be done](https://cygwin.com/cygwin-ug-net/using.html#cygdrive).

MSYS2 should be able to translate paths automatically, so I'm not sure why you're seeing these problems. What are you trying to do?

**Comment by sohnryang** [comment]
It happens if I run commands in neovim like `:!<command-to-execute>`

For example, if I run neovim in msys2 and type `:!ls` or other UNIX commands, it says:

```
/c: /c is a directory
```

**Comment by elieux** [comment]
Maybe I'm just too unfamiliar with neovim, but I don't get it. Why would `ls` complain about something being a directory?

Since I don't see any neovim package in our repositories, I assume your neovim is a regular non-msys2 application, right? Can you point me to where I can download it?

And you're running msys2 programs (like `ls`) from neovim? Does it do anything special to run them? Could you look at the actual executed commands using Process Monitor?

**Comment by sss123next** [comment]
so )

```
(gdb) where
#0  0x00000000776bf3b0 in ntdll!RtlUnhandledExceptionFilter () from /c/Windows/SYSTEM32/ntdll.dll
#1  0x00000000776bf9c6 in ntdll!EtwEnumerateProcessRegGuids () from /c/Windows/SYSTEM32/ntdll.dll
#2  0x00000000776c0592 in ntdll!RtlQueryProcessLockInformation () from /c/Windows/SYSTEM32/ntdll.dll
#3  0x00000000776c2204 in ntdll!RtlLogStackBackTrace () from /c/Windows/SYSTEM32/ntdll.dll
#4  0x000000007765d21c in ntdll!RtlIsDosDeviceName_U () from /c/Windows/SYSTEM32/ntdll.dll
#5  0x000007fefdfa10c8 in msvcrt!free () from /c/Windows/system32/msvcrt.dll
#6  0x000000000040aa50 in Response::FormatV(char const*, char*) ()
#7  0x000000000040aa9d in Response::Format(char const*, ...) ()
#8  0x0000000000406818 in handle_status(Client&, Request, Response&) ()
#9  0x0000000000405497 in command_process(Client&, unsigned int, char*) ()
#10 0x0000000000429798 in client_process_line(Client&, char*) ()
#11 0x000000000040a0d2 in Client::OnSocketInput(void*, unsigned long long) ()
#12 0x0000000001864464 in BufferedSocket::ResumeInput() ()
#13 0x0000000001864b38 in BufferedSocket::OnSocketReady(unsigned int) ()
#14 0x0000000001864258 in SocketMonitor::Dispatch(unsigned int) ()
#15 0x0000000001866d42 in EventLoop::Run() ()
#16 0x0000000000401bd9 in mpd_main(int, char**) ()
#17 0x00000000004013ed in __tmainCRTStartup () at /home/sss/mingw/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:334
#18 0x000000000040152b in mainCRTStartup () at /home/sss/mingw/tmp-gcc-x86_64-w64-mingw32.static/gcc-5.4.0.build_/mingw-w64-v5.0.2/mingw-w64-crt/crt/crtexe.c:212

```

**Comment by elieux** [comment]
No response, closing for now.
