### ISSUE TITLE
Pacman/runtime includes and pod2man missing

### ISSUE THREAD

**Issue by Salamandar** [msys2/msys2#5]
Hi !
I'm trying to install Pacaur. I know it'd be unstable, but hell. Currently I'm compiling its dependency expac-git.
Includes are missing : 

* alpm.h > pacman
* glob.h, pwd.h > glibc

Those headers are actually in` /usr/include` and not `/mingw64/include` so makepkg does not find them.

Additionnaly, the perl binary /usr/bin/core_perl/pod2man is needed but not in the PATH.
The PATH should thus be fixed ;)

**Comment by mati865** [comment]
> Includes are missing :

They are perfectly fine.
Pacman is [MSYS2-package](https://github.com/Alexpux/MSYS2-packages) not mingw one so you have to use `makepkg` instead of `makepkg-mingw`.

> Additionnaly, the perl binary /usr/bin/core_perl/pod2man is needed but not in the PATH.

```
$ which pod2man
/usr/bin/core_perl/pod2man

$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/opt/bin:/c/Windows/System32:/c/Windows:/c/Windows/System32/Wbem:/c/Windows/System32/WindowsPowerShell/v1.0/:/usr/bin/site_perl:/usr/bin/vendor_perl:/usr/bin/core_perl
```

**Comment by Salamandar** [comment]
>  Pacman is MSYS2-package not mingw one so you have to use makepkg instead of makepkg-mingw.
Expac also depends on mingw packages, just like Cower (such as Yajl). So… What should i do ?

**Comment by mati865** [comment]
Probably easiest solution would be to port all packages to msys2-pacakges.

Pinging @mingwandroid, he knows more about this.

**Comment by Salamandar** [comment]
So… I should prefer use/build msys2 packages over mingw ? The wiki and issue comments on sourceforge are not really clear about that.

**Comment by mati865** [comment]
MinGW should be used wherever it is possible. But in this case it doesn't seem possible/easy as you cannot mix msys and mingw libraries.

**Comment by Salamandar** [comment]
OK, I understand you can't mix msys and mingw libs.
But I don't intend to, I just want to compile with the glibc headers. Or is glibc hard to port as mingw64-glibc ?

**Comment by mati865** [comment]
> Or is glibc hard to port as mingw64-glibc ?

I'd rather say it's pointless.
Cygwin, MSYS, MSYS2 are emulating glibc, porting glibc with mingw would
create another Cygwin-like project.

**Comment by mingwandroid** [comment]
It wouldn't be hard, more like close to impossible. You could do it, but the source would no longer resemble glibc.

**Comment by Salamandar** [comment]
Okay :/

**Comment by elieux** [comment]
I don't know how this devolved into a discussion about porting glibc.

@Salamandar, all three header files you mentioned are present in MSYS2 (in `pacman` and `msys2-runtime-devel`). As for the missing packages like Yajl,  you should be able to build them easily for msys2 (you can use Arch Linux PKGBUILDs as starting points).

As for mingw-w64 vs. msys2, if your goal is an extension to pacman, it pretty much implies that it needs to be on the msys2 side of the platform.
