### ISSUE TITLE
fstab mounting does not work for me...

### ISSUE THREAD

**Issue by vincentb1** [msys2/msys2#61]
I am on MSWindows 10. I just installed MSYS2. One difference with the standard installation is that I placed the MSYS2 root directory in `C:\Nos_Programmes\msys64` instead of `C:\msys64`.

When I add to the `/etc/fstab` file the following line:
```
c:/Program\040Files /progs ntfs
```
and I open a shell, typing `mount` does not show `/progs`. In other words, mounting does not work for me.

**Comment by mati865** [comment]
I'd guess space in the path is causing issues.

**Comment by vincentb1** [comment]
I followed the instructions [here](https://cygwin.com/cygwin-ug-net/using.html#mount-table) concerning handling spaces in paths. With MSYS1 the way to handle them was to use `\ ` for spaces (backslash+space) and it was working fine.

**Comment by elieux** [comment]
I think you just didn't finish the line. I added this one to my `/etc/fstab`, and it works:

```
c:/Program\040Files /progs ntfs binary,noacl 0 0
```

Let us know if it helped.

**Comment by vincentb1** [comment]
It worked for me too. Thank you very much. The documentation on the [mount table](http://cygwin.com/cygwin-ug-net/using.html#mount-table) link is not that clear IMHO.
To be noted, the new fstab is taken into account only after closing of _all_ msys bash instances. With msys1 it was taken into account for any new bash instance even though some others were active during the fstab file change.

**Comment by elieux** [comment]
Yeah, it's not super obvious. It only mentions this:

> However, since they are only stored in memory, these mount points will disappear as soon as your last Cygwin process ends.

**Comment by vincentb1** [comment]
I still have one problem. I have a directory `c:/Programmes/MiKTeX 2.9/miktex/bin/x64`, and whether I mount it as `c:/Programmes/MiKTeX\0402.9/miktex/bin/x64` or as `c:/Programmes/MiKTeX\040\062.9/miktex/bin/x64`, the mounting does not work.
To be noted: in the MSWindows explorer there are localized display names, for instance `C:\Users` is displayed as `C:\Utilisateurs`, and `C:\Program Files` is displayed as `C:\Programmes`. This means that the MSWindows explorer shows 2 different directories named `Programmes` under C. One which is the real `C:\Programmes` and the other that is `C:\Program Files` with its localized display name.

**Comment by elieux** [comment]
Key is what is actually on disk. Cygwin doesn't resolve any of that Explorer's shell stuff.

I tried mounting a similar path and had no problem. Your path `c:/Programmes/MiKTeX\0402.9/miktex/bin/x64` should work fine.

**Comment by vincentb1** [comment]
I tried again, and finally it worked. Probably I had some remaining MSYS instance running. Sorry for the additional disturbance, and thank you so much for your support.
