### ISSUE TITLE
timer functions of posix's <time.h> are missing.

### ISSUE THREAD

**Issue by niecore** [msys2/msys2#67]
It seems like that the timer functions of the timer.h file are currently not supported by msys2/mingw64.

What is the reason behind these missing functions?

```
int timer_create(clockid_t, struct sigevent *restrict, timer_t *restrict);
int timer_delete(timer_t);
int timer_getoverrun(timer_t);
int timer_gettime(timer_t, struct itimerspec *);
int timer_settime(timer_t, int, const struct itimerspec *restrict, struct itimerspec *restrict);
```

**Comment by elieux** [comment]
See the man pages for these functions: [timer_create](http://man.he.net/?topic=timer_create&section=2), [timer_delete](http://man.he.net/?topic=timer_delete&section=2), [timer_getoverrun](http://man.he.net/?topic=timer_getoverrun&section=2), [timer_gettime](http://man.he.net/?topic=timer_gettime&section=2), [timer_settime](http://man.he.net/?topic=timer_settime&section=2)

They all say:

> `#include <time.h>`
>
> Link with `-lrt`.

Does including `<time.h>` help?

**Comment by niecore** [comment]
No, unfortunately this does not help. The functions are not declared in the provided header files.

**Comment by elieux** [comment]
Which platform, *msys*, or *mingw*?

**Comment by niecore** [comment]
MinGW-w64 packaged with MSYS2

**Comment by mati865** [comment]
They aren't part of Win32 API.

**Comment by niecore** [comment]
Don't you think, that it would be possible to map the semantics to equivalent win32-api functions? For example: [SetTimer function](https://msdn.microsoft.com/en-us/library/windows/desktop/ms644906(v=vs.85).aspx)

**Comment by mati865** [comment]
I don't know how GHC solved it but you can try it. However be ready for small differences that can cause problems.

**Comment by elieux** [comment]
@mati865, what? How does GHC enter the discussion?

**Comment by mati865** [comment]
GHC is using those functions and I think they solved it some way.

**Comment by niecore** [comment]
I think they are compiling in the linux subsystem of windows 10. [reference](https://www.reddit.com/r/haskell/comments/5t5y4f/linux_subsystem_on_windows_implements_timer/)

btt: Would msys2 be interested in a implementation of the missing functions?

**Comment by elieux** [comment]
> I think they are compiling in the linux subsystem of windows 10.

That's a different thing.  The Linux GHC wasn't working because WSL's implementation was incomplete or incorrect.  This is not applicable to GHC on Win32.

I'm currently looking into Mati's assertion.

> Would msys2 be interested in a implementation of the missing functions?

What would that look like?

**Comment by elieux** [comment]
@mati865, you mean this? https://github.com/ghc/ghc/blob/master/rts/win32/Ticker.c

**Comment by mati865** [comment]
@elieux, it has been a while but I thinks that's it.

2017-08-09 15:59 GMT+02:00 David Macek <notifications@github.com>:

**Comment by elieux** [comment]
@niecore, if interested, you can skip the middleman and propose an implementation to the mingw-w64 project. They should be able to say if it's okay to integrate. Otherwise, there's still an option to make a standalone library.

**Comment by niecore** [comment]
@elieux Okay, thanks for your help.

**Comment by elieux** [comment]
Cheers. If there's any problem, ping me here and I'll try to help. (I'm in contact with mingw-w64, but I don't follow every discussion.)
