### ISSUE TITLE
MinGW64-provided python versions problem with path translation

### ISSUE THREAD

**Issue by jdtournier** [msys2/msys2#7]
There seems to be an issue with the MinGW-provided python versions: they don't translate paths in the `mingw64` folder correctly. The MSYS2-provided version seems to work fine. This creates problems for our build script, which invokes `g++` in a similar manner to the examples below (although this also applies to `os.system()`). 

Note this was all working fine until I updated a few days ago. 

Here's a little example to illustrate the problem. Up to date MSYS2 install as of a few hours ago. There's a C++ file to be compiled, and a python script to invoke the compiler:

#### problem.cpp:
```C++
#include <Eigen/Core>
int main (int argc, char* argv[]) { return 0; }
```

#### problem.py:
```python
import subprocess, sys, os.path

folder = '/mingw64/include/eigen3'
print ('folder: ' + folder)
sys.stdout.flush()

# can we find the folder:
if os.path.isdir (folder):
  print (folder + ' found')
else:
  print (folder + ' NOT found')
sys.stdout.flush()

cmd = ['g++', '-v', '-I'+folder, 'problem.cpp']
print ('cmd: ' + ' '.join(cmd))
sys.stdout.flush()

# adding shell=True makes no difference here:
out = subprocess.check_output (cmd)
#out = subprocess.check_output (cmd, shell=True)
```

#### direct compiler invocation:

No problems there. I'm cutting out 90% of the output, just focusing on the bits that seem to matter, which are the command-line arguments as passed to `g++` - you can see the path to the include folder has been correctly translated:
```
$ g++ -v -I/mingw64/include/eigen3 problem.cpp
...
COLLECT_GCC_OPTIONS='-v' '-I' 'C:/msys64/mingw64/include/eigen3' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
```

#### via python:

Using any version of `python` from MinGW64 fails. The following is using the standard `python`, but this also fails with `python2`, `python3` and `python3.5`. You can see that the path to the include folder hasn't been modified at all, and this means `g++` can't find the corresponding headers:

```
$ python ./problem.py
folder: /mingw64/include/eigen3
/mingw64/include/eigen3 NOT found
cmd: g++ -v -I/mingw64/include/eigen3 problem.cpp
...
COLLECT_GCC_OPTIONS='-v' '-I' '/mingw64/include/eigen3' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
...
problem.cpp:1:22: fatal error: Eigen/Core: No such file or directory
 #include <Eigen/Core>
                      ^
compilation terminated.
Traceback (most recent call last):
  File "./problem.py", line 24, in <module>
    out = subprocess.check_output (cmd)
  File "C:/msys64/mingw64/lib/python3.5\subprocess.py", line 316, in check_output
    **kwargs).stdout
  File "C:/msys64/mingw64/lib/python3.5\subprocess.py", line 398, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['g++', '-v', '-I/mingw64/include/eigen3', 'problem.cpp']' returned non-zero exit status 1
```

However, using `python3.4` works fine, with correct substitution of the include path:

```
$ python3.4 ./problem.py
folder: /mingw64/include/eigen3
/mingw64/include/eigen3 found
cmd: g++ -v -I/mingw64/include/eigen3 problem.cpp
...
COLLECT_GCC_OPTIONS='-v' '-I' 'C:/msys64/mingw64/include/eigen3' '-shared-libgcc' '-mtune=generic' '-march=x86-64'
```

And looking at where these different versions came from, it seems `python3.4` is from MSYS2, the others from MinGW64:
```
$ which python
/mingw64/bin/python
$ which python3
/mingw64/bin/python3
$ which python3.5
/mingw64/bin/python3.5
$ which python3.4
/usr/bin/python3.4
```

Does this make any sense? I assume it's a bug, right?

**Comment by Alexpux** [comment]
Mingw python can't translate POSIX paths because it is native Windows application.

**Comment by jdtournier** [comment]
Darn, of course. I was actually [reading about this](https://github.com/msys2/msys2/wiki/How-does-MSYS2-differ-from-Cygwin) earlier today... :man_facepalming: 

Simplest fix is to remove all the MinGW python versions, I guess. Certainly seems to do the trick. Thanks!
