### ISSUE TITLE
mingw-w64-x86_64-cmake missing libidn2 dependecy

### ISSUE THREAD

**Issue by mikcza** [msys2/msys2#72]
Even though ```zlib``` was installed when trying to run cmake the following error appears:

```
C:/msys64/mingw64/bin/cmake.exe: error while loading shared libraries: zlib1.dll                                                : cannot open shared object file: No such file or directory
```

Installing ```mingw-w64-x86_64-libidn2``` solved the issue.

**Comment by lazka** [comment]
See https://github.com/Alexpux/MINGW-packages/issues/2803

**Comment by elieux** [comment]
Looks fixed then. Thanks @lazka.
