### ISSUE TITLE
Alternative or Support for 'parallel' package from arch 'Community' repository?

### ISSUE THREAD

**Issue by FrantzelasG** [msys2/msys2#77]
I run the command pacman -Ss parallel, but i got nothing. Can we make msys2 work with standard arch repositories, namely community? Or can we build 'parallel' from source hosted in gnu-ftp-website?
#Update0: tried this: pacman -U http://ftp.gnu.org/gnu/parallel/parallel-latest.tar.bz2 (got pgp sig problem)

**Comment by FrantzelasG** [comment]
Instructions on how to install package: parallel from repository: community -- msys2/archlinux
Ok i solved it: For anyone interested: its 3 steps:
1) nano /etc/pacman.conf (add 3lines) on the bottom of the file under msys2 repo

[community]
Include = /etc/pacman.d/mirrorlist.community

2) cd /etc/pacman.d
nano mirrorlist.community
copy-paste: Server = http://mirrors.kernel.org/archlinux/community/os/x86_64

3) run: pacman -Syy
run: pacman -S parallel

**Comment by mati865** [comment]
Mixing MSYS2 and Arch Linux repositories is one of the worst ideas I've seen so far.

**Comment by elieux** [comment]
I suggest you take great care when doing that, @FrantzelasG.  Only `arch=any` ("noarch") packages can be expected to work, and even then it's a game of chance.

The correct way for you to get GNU Parallel to your MSYS2 installation is to build it from source.  You found the correct link, but you can't just feed it to `pacman -U`, you need to follow the [building instructions](https://git.savannah.gnu.org/cgit/parallel.git/tree/README).
