### ISSUE TITLE
Don't recognize backslash "\\" of path in Windows

### ISSUE THREAD

**Issue by qilingit** [msys2/msys2#78]
I am using MSYS2-32 bit in Windows 10 to compil a "libwdi": https://github.com/pbatard/libwdi, but msys2 don't recognize backslash of the path of library that I've set. In fact, in the header file, the path is like this: "`{ 0, DDK_DIR "\\redist\\wdf\\x86\\WdfCoInstaller0" STR(WDF_VER) ".dll", "x86" }`", the msys2 think that "`\`" is a backlash, but not "`\\`", so this produce many warnings like:

```
In file included from embedder.c:48:0:
embedder_files.h:47:67: warning: unknown escape sequence: '\P'
   { 0, DDK_DIR "\\redist\\wdf\\x86\\WdfCoInstaller0" STR(WDF_VER) ".dll", "x86" },
                                                                   ^~~~~~
embedder_files.h:47:67: warning: unknown escape sequence: '\W'
embedder_files.h:48:45: warning: unknown escape sequence: '\P'
   { 0, DDK_DIR "\\redist\\" COINSTALLER_DIR "\\x86\\winusbcoinstaller2.dll", "x86" },
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
embedder_files.h:48:45: warning: unknown escape sequence: '\W'
  CC       installer_x86-installer.o
  CCLD     installer_x86.exe
```

And these warnings produce error of path of library:

```
embedder_files.h:48:45: warning: unknown escape sequence: '\W'
  CC       installer_x86-installer.o
  CCLD     installer_x86.exe
  EMBED  C:\Users\qzhang\Documents\AutoUSB\libwdi-mingw\libwdi\Program Files (x86)Windows Kit\redist\wdf\x86\WdfCoInstaller01011.dll embedder : error: Could not open file 'C:\Users\qzhang\Documents\AutoUSB\libwdi-mingw\libwdi\Program Files (x86)Windows Kit\redist\wdf\x86\WdfCoInstaller01011.dll'.
make[2]: *** [Makefile:875: embedded.h] Error 1
make[2]: Leaving directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw/libwdi'
make[1]: *** [Makefile:411: all-recursive] Error 1
make[1]: Leaving directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw'
make: *** [Makefile:343: all] Error 2
```

Can anyone help me to solve this problem? Thanks.

**Comment by elieux** [comment]
What commands did you use to build?

**Comment by qilingit** [comment]
Thanks @elieux.
I use ./configure to generate the MakeFile, and then I use "make" to build, I don't know which command I should use to list all the packages that I have installed which I want to show you.

**Comment by elieux** [comment]
Can you give the exact `./configure ...` line?

**Comment by qilingit** [comment]
@elieux 
I am in Windows 10 Pro,  64 bits, I want to use `MSYS2 MinGW 64-bit` to build a 32 bits, I use
 `./configure --with-ddkdir="C:\Program Files (x86)\Windows Kits\10" --enable-64bit=no
,` 
to configure, and then I got:

`configure: loading site script /mingw64/etc/config.site
checking for a BSD-compatible install... /usr/bin/install -c
checking whether build environment is sane... yes
checking for a thread-safe mkdir -p... /usr/bin/mkdir -p
checking for gawk... gawk
checking whether make sets $(MAKE)... yes
checking whether make supports nested variables... yes
checking whether make supports nested variables... (cached) yes
checking for gcc... gcc
checking whether the C compiler works... yes
checking for C compiler default output file name... a.exe
checking for suffix of executables... .exe
checking whether we are cross compiling... no
checking for suffix of object files... o
checking whether we are using the GNU C compiler... yes
checking whether gcc accepts -g... yes
checking for gcc option to accept ISO C89... none needed
checking whether gcc understands -c and -o together... yes
checking for style of include used by make... GNU
checking dependency style of gcc... gcc3
checking build system type... x86_64-w64-mingw32
checking host system type... x86_64-w64-mingw32
checking how to print strings... printf
checking for a sed that does not truncate output... /usr/bin/sed
checking for grep that handles long lines and -e... /usr/bin/grep
checking for egrep... /usr/bin/grep -E
checking for fgrep... /usr/bin/grep -F
checking for ld used by gcc... C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe
checking if the linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) is GNU ld... yes
checking for BSD- or MS-compatible name lister (nm)... /mingw64/bin/nm -B
checking the name lister (/mingw64/bin/nm -B) interface... BSD nm
checking whether ln -s works... no, using cp -pR
checking the maximum length of command line arguments... 8192
checking how to convert x86_64-w64-mingw32 file names to x86_64-w64-mingw32 format... func_convert_file_msys_to_w32
checking how to convert x86_64-w64-mingw32 file names to toolchain format... func_convert_file_msys_to_w32
checking for C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe option to reload object files... -r
checking for objdump... objdump
checking how to recognize dependent libraries... file_magic ^x86 archive import|^x86 DLL
checking for dlltool... dlltool
checking how to associate runtime and link libraries... func_cygming_dll_for_implib
checking for ar... ar
checking for archiver @FILE support... @
checking for strip... strip
checking for ranlib... ranlib
checking command to parse /mingw64/bin/nm -B output from gcc object... ok
checking for sysroot... no
checking for a working dd... /usr/bin/dd
checking how to truncate binary pipes... /usr/bin/dd bs=4096 count=1
checking for mt... no
checking if : is a manifest tool... no
checking how to run the C preprocessor... gcc -E
checking for ANSI C header files... yes
checking for sys/types.h... yes
checking for sys/stat.h... yes
checking for stdlib.h... yes
checking for string.h... yes
checking for memory.h... yes
checking for strings.h... yes
checking for inttypes.h... yes
checking for stdint.h... yes
checking for unistd.h... yes
checking for dlfcn.h... no
checking for objdir... .libs
checking if gcc supports -fno-rtti -fno-exceptions... no
checking for gcc option to produce PIC... -DDLL_EXPORT -DPIC
checking if gcc PIC flag -DDLL_EXPORT -DPIC works... yes
checking if gcc static flag -static works... yes
checking if gcc supports -c -o file.o... yes
checking if gcc supports -c -o file.o... (cached) yes
checking whether the gcc linker (C:/msys64/mingw64/x86_64-w64-mingw32/bin/ld.exe) supports shared libraries... yes
checking whether -lc should be explicitly linked in... yes
checking dynamic linker characteristics... Win32 ld.exe
checking how to hardcode library paths into programs... immediate
checking whether stripping libraries is possible... yes
checking if libtool supports shared libraries... yes
checking whether to build shared libraries... yes
checking whether to build static libraries... yes
checking for windres... windres
checking for inline... inline
checking development environment... MinGW
checking whether the build compiler can produce executables that run on this host... yes
checking whether the compiler can produce 32 bit binaries... yes
checking whether the compiler can produce 64 bit binaries... yes
configure: will produce 32 bit library and samples, compatible with 64 bit platforms
configure: if you want to produce 64 bit only library and samples, use --disable-32bit
checking for C:\Program Files (x86)\Windows Kits\10/redist/winusb/... no
checking for C:\Program Files (x86)\Windows Kits\10/redist/wdf/x64/... yes
checking for C:\Program Files (x86)\Windows Kits\10/redist/wdf/x64/WdfCoInstaller01011.dll... yes
checking for C:\Program Files (x86)\Windows Kits\10/redist/wdf/x64/winusbcoinstaller2.dll... yes
checking for C:\Program Files (x86)\Windows Kits\10/redist/wdf/x86/WdfCoInstaller01011.dll... yes
checking for C:\Program Files (x86)\Windows Kits\10/redist/wdf/x86/winusbcoinstaller2.dll... yes
checking that generated files are newer than configure... done
configure: creating ./config.status
config.status: creating Makefile
config.status: creating libwdi/Makefile
config.status: creating libwdi/libwdi.pc
config.status: creating examples/Makefile
config.status: creating config.h
config.status: config.h is unchanged
config.status: executing depfiles commands
config.status: executing libtool commands
`

And then I `make`, I got:

`make[1]: Entering directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw-64/libwdi'
test -z "libwdi.la" || rm -f libwdi.la
rm -f ./so_locations
rm -rf .libs _libs
rm -rf embedded.h embedder embedder.exe
 rm -f installer_x86.exe installer_x64.exe
 rm -f installer_x86 installer_x64
rm -f *.o
rm -f *.lo
make[1]: Leaving directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw-64/libwdi'
make[1]: Entering directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw-64'
rm -rf .libs _libs
rm -f *.lo
make[1]: Leaving directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw-64'
make  all-recursive
make[1]: Entering directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw-64'
Making all in libwdi
make[2]: Entering directory '/c/Users/qzhang/Documents/AutoUSB/libwdi-mingw-64/libwdi'
  CCLD   embedder
In file included from embedder.c:48:0:
embedder_files.h:47:67: warning: unknown escape sequence: '\P'
   { 0, DDK_DIR "\\redist\\wdf\\x86\\WdfCoInstaller0" STR(WDF_VER) ".dll", "x86" },
                                                                   ^~~~~~
embedder_files.h:47:67: warning: unknown escape sequence: '\W'
embedder_files.h:48:45: warning: unknown escape sequence: '\P'
   { 0, DDK_DIR "\\redist\\" COINSTALLER_DIR "\\x86\\winusbcoinstaller2.dll", "x86" },
                                             ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
embedder_files.h:48:45: warning: unknown escape sequence: '\W'
embedder_files.h:51:75: warning: unknown escape sequence: '\P'
   { 0, DDK_DIR "\\redist\\wdf\\" X64_DIR "\\WdfCoInstaller0" STR(WDF_VER) ".dll", "amd64" },
                                                                           ^~~~~~
embedder_files.h:51:75: warning: unknown escape sequence: '\W'
embedder_files.h:52:58: warning: unknown escape sequence: '\P'
   { 0, DDK_DIR "\\redist\\" COINSTALLER_DIR "\\" X64_DIR "\\winusbcoinstaller2.dll", "amd64" },
                                                          ^~~~~~~~~~~~~~~~~~~~~~~~~~
embedder_files.h:52:58: warning: unknown escape sequence: '\W'
  CC       installer_x86-installer.o
  CCLD     installer_x86.exe
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib/libsetupapi.a when searching for -lsetupapi
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: skipping incompatible C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/7.2.0/../../../../x86_64-w64-mingw32/lib\libsetupapi.a when searching for -lsetupapi
`

Thanks.

**Comment by elieux** [comment]
1. I assume you mean `--with-wdkdir`.
2. You're using backslashes wrong. I think it would be better to write `"C:/Program Files (x86)/Windows Kits/10"` in which case you don't have to think about properly escaping backslashes.
3. I suggest you build 32-bit binaries with the 32-bit shell. Our GCC builds don't support "cross-bits" compiling.

**Comment by qilingit** [comment]
Thanks for your answers. 

1, Because we use mingw to compile, so I think it's `--with-ddkdir`, and I tryed it, if we use `--with-wdkdir`,  there will be an error.
2, Thanks for this, il seems like that's run if I changed it to `"C:/Program Files (x86)/Windows Kits/10"`, and now there is a problem with their library libwdi, which I think I can resolve.
3, It really runs when I build with the 32-bit shell.

**Comment by elieux** [comment]
1] Which version of Libwdi are you using? My `./configure --help` doesn't mention `--with-ddkdir`:

```
  --with-wdkdir           embed WinUSB driver files from the following WDK
                          location
  --with-wdfver           WDF/KDMF version to use (default 1011)
  --with-libusb0          embed libusb0 driver files from the following
                          location
  --with-libusbk          embed libusbK driver files from the following
                          location
  --with-userdir          embed user defined driver files from the following
                          location
```

When I do `--with-ddkdir`, it fails with:
```
configure: error: One of --with-wdkdir, --with-libusb0, --with-libusbk or --with-userdir options MUST be provided.
```

2+3] Great.

I guess I can close this ticket now, but if you need any further help, just say.

**Comment by qilingit** [comment]
I am using `libwdi v1.3.0` which a release version, I've compiled successfully once with Visual Studio 2017(VS), if a remembered good, in VS, it was `--with-wdkdir`. 

Thanks for your answers.
