### ISSUE TITLE
Is there a way to statically build a program that can run without msys-2.0.dll?

### ISSUE THREAD

**Issue by TooYoungTooSimp** [msys2/msys2#79]
I found a file `/usr/lib/libmsys-2.0.a`.
So I have tried `g++ -lmsys-2.0 -static` but it didn't work.

**Comment by elieux** [comment]
First make sure you can comply with the LGPL license if you link statically.  Then I suggest searching the Internet for mentions of statically linking with `cygwin1.dll`, which should be a way more popular question, so you'll have better chances of finding an answer.  The steps for doing that should apply to `msys-2.0.dll` as well.  If you find out how to do that, please let us know.

**Comment by TooYoungTooSimp** [comment]
Thank you for your reply.
What I compile is used by myself only or fully opensource. There is no license problem.
I am trying to find out answer with your guide.

**Comment by TooYoungTooSimp** [comment]
After a long search, I can't find the solution by myself.
The official site of cygwin says 
> [No. If your program uses the Cygwin API, then your executable cannot run without cygwin1.dll](https://cygwin.com/faq/faq.html#faq.programming.static-linking)

I've tried this `g++ -static -lmsys-2.0 1.cpp` (only a hello world), but it returned
```
/tmp/ccSxu0X3.o:1.cpp:(.text+0x0): multiple definition of `main'
/usr/lib/../lib/libmsys-2.0.a(libcmain.o):/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/lib/libcmain.c:16: first defined here
/usr/lib/../lib/libmsys-2.0.a(libcmain.o): In function `main':
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/lib/libcmain.c:37: undefined reference to `WinMain'
/msys_scripts/msys2-runtime/src/msys2-runtime/winsup/cygwin/lib/libcmain.c:37:(.text.startup+0x94): relocation truncated to fit: R_X86_64_PC32 against undefined symbol `WinMain'
collect2: error: ld returned 1 exit status
```
It seems that ld tried to link libmsys-2.0.a but failed.

**Comment by elieux** [comment]
Hmm.  I tried to research that myself and it *seems* it's really not possible.  Sorry for misleading you.
