### ISSUE TITLE
Can't build podofo 0.9.5 (but can build PDF Hummus)

### ISSUE THREAD

**Issue by mark-summerfield** [msys2/msys2#8]
I have tried building podofo 0.9.5 since the pre-built 0.9.3 is 3 years old, but I couldn't get it to build.

However, I did manage to build https://github.com/galkahana/PDF-Writer (aka PDF Hummus) which is also a cmake-based build. And the test .exe seems to work for some of its tests. But I'm more interested in podofo:-)

I also found I had to add these two lines to the .bashrc file to have a working path:
```sh
export PATH=/c/msys64/bin:/c/msys64/usr/bin:$PATH
cd /c/msys64/home/mark
```

**Comment by elieux** [comment]
What was the error in building podofo?

PATH should be working by default. What was wrong with it before the `.bashrc` modifications?

**Comment by mark-summerfield** [comment]
Sorry, I can't remember now. I put it in a virtualbox Windows and have deleted that snapshot now.

**Comment by elieux** [comment]
I will tentatively close this issue, but if you ever get back to building podofo, it can be reopened.
