### ISSUE TITLE
Wget not able to use CA certs after recent update

### ISSUE THREAD

**Issue by StarWolf3000** [msys2/msys2#83]
I did the recent update for the ca-certificates (20170717-1) and now wget and other tools cannot use the certificates anymore. I checked the usual location at `/usr/ssl/certs/` and both `ca-bundle.crt` and `ca-bundle.trust.crt` are empty (0 bytes). Then I did a reinstall with pacman, just to make sure something didn't go wrong, and it happened again.

After manually downloading and examining the package file, I found that the .crt files at the common locations are empty too in the .xz. However I found a ~2 MiB .crt at `/usr/share/pki/ca-trust-source/` instead (the same path as in the package file).

Do I have to edit my wgetrc to point to that file instead?

Edit:
`ca_certificate=/usr/share/pki/ca-trust-source/ca-bundle.trust.crt` ?

**Comment by Alexpux** [comment]
Post all MSYS2 packages related issues to https://github.com/Alexpux/MSYS2-packages/issues
But before verify that no one already report it.
