### ISSUE TITLE
GCC 7 / Clang 5 (with libc++)

### ISSUE THREAD

**Issue by WPMGPRoSToTeMa** [msys2/msys2#9]
Can I compile and use GCC 7 or Clang 5 (with libc++) on MinGW? Or I should wait for its release and ready packages for MinGW?
Clang for Windows is not for me, because it uses MSVC C++ headers, I want to use the latest features from C++17 STL.

**Comment by mati865** [comment]
Libc++ does build with big amount of hacks but it's far from being usable even for hello world programs.

You can build https://github.com/Alexpux/MINGW-packages/tree/master/mingw-w64-gcc-git but change branch to master. But keep in mind that master branch may gets broken from time to time.

**Comment by elieux** [comment]
I'm closing this ticket because it doesn't track any real issue IMO. You can still discuss here.
